### ISSUE TITLE
[CI] [Report] Errors from 1.5 all plugins test 

### ISSUE THREAD

**Issue by purbon** [logstash-plugins/logstash-filter-translate#9]
Seen: http://build-eu-00.elastic.co/view/LS%201.5/job/Logstash_1.5_All_Plugins_test/772/console

```
  4) LogStash::Filters::Translate fallback value - allow sprintf "{"status":"200","missing_translation":"no match"}" when processed
     Failure/Error: insist { subject["translation"] } == "no match"
     Insist::Failure:
       Expected "no match", but got nil
     # ./vendor/bundle/jruby/1.9/gems/insist-1.0.0/lib/insist/assert.rb:8:in `assert'
     # ./vendor/bundle/jruby/1.9/gems/insist-1.0.0/lib/insist/comparators.rb:14:in `=='
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-translate-0.1.9/spec/filters/translate_spec.rb:98:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
```

**Comment by wiibaa** [comment]
Running this on a windows machine, I got:
````
Something went wrong when attempting to translate from dictionary {:exception=>#<RuntimeError: expected UTF-8 encoding for value=no match, encoding=#<Encoding:US-ASCII>>, :field=>"status", 
[...]
````

Adding the `# encoding: utf-8` header to translate_spec.rb fixes this, see PR #10
